services:
  # A Docker web service
  - type: web
    name: kakao_ai_agent_v0.1
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
